In [158]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [159]:
df = pd.read_csv('/PyAi/tes linier regression/tplink dataset.csv', sep=';')
df.head()

,Date,Last Crawling,SKU Name,Product Name,Url Product,Seller,Merchant,Stock,Item Condition,Filter,Flag,Bottom Price,Original Price,Discount,Selling Price,Discrepancy,Sales Quantity,Sales Revenue
0,"Oct 22, 2022","Oct 22, 2022",TL WR840N,TP-Link TL-WR840N 2 Antenna 300Mbps Wireless N...,https://tokopedia.com/ccplace/tp-link-tl-wr840...,ccplace shop,tokopedia,In Stock,baru,Above,Please Check,155000.0,231000,0,231000.0,"0,014903226",0.0,0.0
1,"Oct 22, 2022","Oct 22, 2022",TL WR840N,Promo TP-LINK TL-WR840N Wireless Router 300Mbp...,https://tokopedia.com/gilsaashopp/promo-tp-lin...,gilsaa_shopp,tokopedia,In Stock,baru,Above,Please Check,155000.0,218800,0,218800.0,"0,014116129",0.0,0.0
2,"Oct 22, 2022","Oct 22, 2022",TL WR840N,Tp-Link TL-WR840N 300Mbps Wireless N Speed Rou...,https://tokopedia.com/ccwinta/tp-link-tl-wr840...,ccwinta shop,tokopedia,In Stock,baru,Above,Please Check,155000.0,227000,0,227000.0,"0,014645161",0.0,0.0
3,"Oct 22, 2022","Oct 22, 2022",TL WR840N,JARINGAN TP-LINK TL-WR 840N TL-WR840N 300MBps ...,https://tokopedia.com/belsa/jaringan-tp-link-t...,BELSA_SHOP,tokopedia,In Stock,baru,Above,Please Check,155000.0,263000,0,263000.0,"0,016967742",0.0,0.0
4,"Oct 22, 2022","Oct 22, 2022",TL WR840N,TPLink TL-WR840N Router Wireless WiFi 300Mbps ...,https://tokopedia.com/ccwinta/tplink-tl-wr840n...,ccwinta shop,tokopedia,In Stock,baru,Above,Please Check,155000.0,236000,0,236000.0,"0,015225806",0.0,0.0

In [160]:
#untuk mengetahui bentuk dataset, berapa kolom dan berapa baris
df.shape

(27794, 18)

In [161]:
#untuk mengetahui data yang memiliki missing value
df.isnull().sum()

Date              25785
Last Crawling     25785
SKU Name          25785
Product Name      25785
Url Product       25785
Seller            25785
Merchant          25785
Stock             25785
Item Condition    25785
Filter            25785
Flag              25785
Bottom Price      25785
Original Price    25785
Discount          25785
Selling Price     25785
Discrepancy       25785
Sales Quantity    25785
Sales Revenue     25785
dtype: int64

In [162]:
#menghapus missing value agar tidak membingungkan ketika data telah dicoba
df.dropna()

,Date,Last Crawling,SKU Name,Product Name,Url Product,Seller,Merchant,Stock,Item Condition,Filter,Flag,Bottom Price,Original Price,Discount,Selling Price,Discrepancy,Sales Quantity,Sales Revenue
0,"Oct 22, 2022","Oct 22, 2022",TL WR840N,TP-Link TL-WR840N 2 Antenna 300Mbps Wireless N...,https://tokopedia.com/ccplace/tp-link-tl-wr840...,ccplace shop,tokopedia,In Stock,baru,Above,Please Check,155000.0,231000,0,231000.0,"0,014903226",0.0,0.0
1,"Oct 22, 2022","Oct 22, 2022",TL WR840N,Promo TP-LINK TL-WR840N Wireless Router 300Mbp...,https://tokopedia.com/gilsaashopp/promo-tp-lin...,gilsaa_shopp,tokopedia,In Stock,baru,Above,Please Check,155000.0,218800,0,218800.0,"0,014116129",0.0,0.0
2,"Oct 22, 2022","Oct 22, 2022",TL WR840N,Tp-Link TL-WR840N 300Mbps Wireless N Speed Rou...,https://tokopedia.com/ccwinta/tp-link-tl-wr840...,ccwinta shop,tokopedia,In Stock,baru,Above,Please Check,155000.0,227000,0,227000.0,"0,014645161",0.0,0.0
3,"Oct 22, 2022","Oct 22, 2022",TL WR840N,JARINGAN TP-LINK TL-WR 840N TL-WR840N 300MBps ...,https://tokopedia.com/belsa/jaringan-tp-link-t...,BELSA_SHOP,tokopedia,In Stock,baru,Above,Please Check,155000.0,263000,0,263000.0,"0,016967742",0.0,0.0
4,"Oct 22, 2022","Oct 22, 2022",TL WR840N,TPLink TL-WR840N Router Wireless WiFi 300Mbps ...,https://tokopedia.com/ccwinta/tplink-tl-wr840n...,ccwinta shop,tokopedia,In Stock,baru,Above,Please Check,155000.0,236000,0,236000.0,"0,015225806",0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2004,"Oct 15, 2022","Oct 15, 2022",TL WR840N,Wireless Router TP-Link TL-WR840N,https://shopee.co.id/Wireless-Router-TP-Link-T...,HnD Computer,shopee,In Stock,baru,Equal,-,155000.0,155000,0,155000.0,0,0.0,0.0
2005,"Oct 15, 2022","Oct 15, 2022",TL WR840N,Tp-Link / Tplink Tl-Wr840N Wireless-N300 Router,https://shopee.co.id/Tp-Link-Tplink-Tl-Wr840N-...,Seleniumhoki,shopee,In Stock,baru,Above,Please Check,155000.0,227000,0,227000.0,"0,014645161",0.0,0.0
2006,"Oct 15, 2022","Oct 15, 2022",TL WR840N,TP-Link / TPLink TL-WR840N Wireless-N300 Route...,https://shopee.co.id/TP-Link-TPLink-TL-WR840N-...,Ade99 Shop,shopee,In Stock,baru,Above,Please Check,155000.0,220000,0,220000.0,"0,014193548",0.0,0.0
2007,"Oct 15, 2022","Oct 15, 2022",TL WR840N,TP-LINK TPLINK TL-WR840N Wireless N Router Rep...,https://shopee.co.id/TP-LINK-TPLINK-TL-WR840N-...,007bestseller,shopee,In Stock,baru,Above,Please Check,155000.0,214000,0,214000.0,"0,013806452",0.0,0.0
2008,"Oct 15, 2022","Oct 15, 2022",TL WR840N,TP-LINK TL-WR840N 300Mbps Wireless N Router,https://shopee.co.id/TP-LINK-TL-WR840N-300Mbps...,hiasinta24collections,shopee,In Stock,baru,Above,Please Check,155000.0,410000,0,410000.0,"0,026451613",0.0,0.0

In [164]:
#mengetahui data yang duplikatt
df.duplicated().sum()

np.int64(25784)

In [165]:
#hapus data duplikat
df.drop_duplicates()

,Date,Last Crawling,SKU Name,Product Name,Url Product,Seller,Merchant,Stock,Item Condition,Filter,Flag,Bottom Price,Original Price,Discount,Selling Price,Discrepancy,Sales Quantity,Sales Revenue
0,"Oct 22, 2022","Oct 22, 2022",TL WR840N,TP-Link TL-WR840N 2 Antenna 300Mbps Wireless N...,https://tokopedia.com/ccplace/tp-link-tl-wr840...,ccplace shop,tokopedia,In Stock,baru,Above,Please Check,155000.0,231000,0,231000.0,"0,014903226",0.0,0.0
1,"Oct 22, 2022","Oct 22, 2022",TL WR840N,Promo TP-LINK TL-WR840N Wireless Router 300Mbp...,https://tokopedia.com/gilsaashopp/promo-tp-lin...,gilsaa_shopp,tokopedia,In Stock,baru,Above,Please Check,155000.0,218800,0,218800.0,"0,014116129",0.0,0.0
2,"Oct 22, 2022","Oct 22, 2022",TL WR840N,Tp-Link TL-WR840N 300Mbps Wireless N Speed Rou...,https://tokopedia.com/ccwinta/tp-link-tl-wr840...,ccwinta shop,tokopedia,In Stock,baru,Above,Please Check,155000.0,227000,0,227000.0,"0,014645161",0.0,0.0
3,"Oct 22, 2022","Oct 22, 2022",TL WR840N,JARINGAN TP-LINK TL-WR 840N TL-WR840N 300MBps ...,https://tokopedia.com/belsa/jaringan-tp-link-t...,BELSA_SHOP,tokopedia,In Stock,baru,Above,Please Check,155000.0,263000,0,263000.0,"0,016967742",0.0,0.0
4,"Oct 22, 2022","Oct 22, 2022",TL WR840N,TPLink TL-WR840N Router Wireless WiFi 300Mbps ...,https://tokopedia.com/ccwinta/tplink-tl-wr840n...,ccwinta shop,tokopedia,In Stock,baru,Above,Please Check,155000.0,236000,0,236000.0,"0,015225806",0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2005,"Oct 15, 2022","Oct 15, 2022",TL WR840N,Tp-Link / Tplink Tl-Wr840N Wireless-N300 Router,https://shopee.co.id/Tp-Link-Tplink-Tl-Wr840N-...,Seleniumhoki,shopee,In Stock,baru,Above,Please Check,155000.0,227000,0,227000.0,"0,014645161",0.0,0.0
2006,"Oct 15, 2022","Oct 15, 2022",TL WR840N,TP-Link / TPLink TL-WR840N Wireless-N300 Route...,https://shopee.co.id/TP-Link-TPLink-TL-WR840N-...,Ade99 Shop,shopee,In Stock,baru,Above,Please Check,155000.0,220000,0,220000.0,"0,014193548",0.0,0.0
2007,"Oct 15, 2022","Oct 15, 2022",TL WR840N,TP-LINK TPLINK TL-WR840N Wireless N Router Rep...,https://shopee.co.id/TP-LINK-TPLINK-TL-WR840N-...,007bestseller,shopee,In Stock,baru,Above,Please Check,155000.0,214000,0,214000.0,"0,013806452",0.0,0.0
2008,"Oct 15, 2022","Oct 15, 2022",TL WR840N,TP-LINK TL-WR840N 300Mbps Wireless N Router,https://shopee.co.id/TP-LINK-TL-WR840N-300Mbps...,hiasinta24collections,shopee,In Stock,baru,Above,Please Check,155000.0,410000,0,410000.0,"0,026451613",0.0,0.0
2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [166]:
#melihat list kolom
df.columns.tolist()

['Date',
 'Last Crawling',
 'SKU Name',
 'Product Name',
 'Url Product',
 'Seller',
 'Merchant',
 'Stock',
 'Item Condition',
 'Filter',
 'Flag',
 'Bottom Price',
 'Original Price',
 'Discount',
 'Selling Price',
 'Discrepancy',
 'Sales Quantity',
 'Sales Revenue']

In [167]:
#melihat nilai unik dari atribut SKU Name
df['SKU Name'].unique()

<StringArray>
['TL WR840N', nan]
Length: 2, dtype: str

In [175]:
df['Url Product'].unique()

<StringArray>
[                                 'https://tokopedia.com/ccplace/tp-link-tl-wr840n-2-antenna-300mbps-wireless-n-router',
                             'https://tokopedia.com/gilsaashopp/promo-tp-link-tl-wr840n-wireless-router-300mbps-diskon',
                  'https://tokopedia.com/ccwinta/tp-link-tl-wr840n-300mbps-wireless-n-speed-router-wifi-840-840n-wr840',
                          'https://tokopedia.com/belsa/jaringan-tp-link-tl-wr-840n-tl-wr840n-300mbps-wireless-router-2',
                  'https://tokopedia.com/ccwinta/tplink-tl-wr840n-router-wireless-wifi-300mbps-2-antena-tp-link-wr840n',
                              'https://tokopedia.com/garwitastore-i/tp-link-tl-wr840n-antenna-300mbps-wireless-n-promo',
                                                               'https://tokopedia.com/ccplace/tp-link-wr840n-tl-wr840n',
                  'https://tokopedia.com/nugrahaabadi123/tp-link-tl-wr840n-300mbps-tplink-wifi-wireless-n-router-wr840',
 'https://tokopedia.com/brantaofficial/ready-stok-tp-link-router-tl-wr820n-tl-wr844n-tl-wr840n-300n-terbaik-tl-wr8420n',
                  'https://tokopedia.com/fatah-2/tplink-tl-wr840n-router-wireless-wifi-300mbps-2-antena-tp-link-wr840n',
 ...
                   'https://tokopedia.com/ghithas/tp-link-tl-wr840n-wireless-n-router-300-mbps-wr840n-840n-840-garansi',
                                            'https://tokopedia.com/ghithas/wireless-n-router-tp-link-tl-wr840n-300mbps',
                              'https://shopee.co.id/TP-Link-TL-WR840N-300Mbps-Wireless-N-Router-i.224602937.9316136446',
                      'https://shopee.co.id/TP-LINK-TL-WR840N-300Mbps-Wireless-Router-ORIGINAL-i.160000465.14662733514',
                                        'https://shopee.co.id/Wireless-Router-TP-Link-TL-WR840N-i.192632120.9853694510',
                            'https://shopee.co.id/Tp-Link-Tplink-Tl-Wr840N-Wireless-N300-Router-i.316979025.8003037960',
                      'https://shopee.co.id/TP-Link-TPLink-TL-WR840N-Wireless-N300-Router-Promo-i.125762532.8317480826',
     'https://shopee.co.id/TP-LINK-TPLINK-TL-WR840N-Wireless-N-Router-Repeater-Access-Point-AP-i.530381506.21217841398',
                             'https://shopee.co.id/TP-LINK-TL-WR840N-300Mbps-Wireless-N-Router-i.205071983.12833750705',
                                                                                                                    nan]
Length: 2010, dtype: str

In [168]:
df.drop(columns=['Date', 'Seller', 'Merchant', 'Stock', 'Item Condition', 'Filter', 'Flag', 'Discount', 'Discrepancy', 'Sales Quantity', 'Sales Revenue'], inplace=True)

In [169]:
df.columns.tolist()

['Last Crawling',
 'SKU Name',
 'Product Name',
 'Url Product',
 'Bottom Price',
 'Original Price',
 'Selling Price']

In [170]:
df

,Last Crawling,SKU Name,Product Name,Url Product,Bottom Price,Original Price,Selling Price
0,"Oct 22, 2022",TL WR840N,TP-Link TL-WR840N 2 Antenna 300Mbps Wireless N...,https://tokopedia.com/ccplace/tp-link-tl-wr840...,155000.0,231000,231000.0
1,"Oct 22, 2022",TL WR840N,Promo TP-LINK TL-WR840N Wireless Router 300Mbp...,https://tokopedia.com/gilsaashopp/promo-tp-lin...,155000.0,218800,218800.0
2,"Oct 22, 2022",TL WR840N,Tp-Link TL-WR840N 300Mbps Wireless N Speed Rou...,https://tokopedia.com/ccwinta/tp-link-tl-wr840...,155000.0,227000,227000.0
3,"Oct 22, 2022",TL WR840N,JARINGAN TP-LINK TL-WR 840N TL-WR840N 300MBps ...,https://tokopedia.com/belsa/jaringan-tp-link-t...,155000.0,263000,263000.0
4,"Oct 22, 2022",TL WR840N,TPLink TL-WR840N Router Wireless WiFi 300Mbps ...,https://tokopedia.com/ccwinta/tplink-tl-wr840n...,155000.0,236000,236000.0
...,...,...,...,...,...,...,...
27789,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27790,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27791,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27792,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27793,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [171]:
df.dropna()

,Last Crawling,SKU Name,Product Name,Url Product,Bottom Price,Original Price,Selling Price
0,"Oct 22, 2022",TL WR840N,TP-Link TL-WR840N 2 Antenna 300Mbps Wireless N...,https://tokopedia.com/ccplace/tp-link-tl-wr840...,155000.0,231000,231000.0
1,"Oct 22, 2022",TL WR840N,Promo TP-LINK TL-WR840N Wireless Router 300Mbp...,https://tokopedia.com/gilsaashopp/promo-tp-lin...,155000.0,218800,218800.0
2,"Oct 22, 2022",TL WR840N,Tp-Link TL-WR840N 300Mbps Wireless N Speed Rou...,https://tokopedia.com/ccwinta/tp-link-tl-wr840...,155000.0,227000,227000.0
3,"Oct 22, 2022",TL WR840N,JARINGAN TP-LINK TL-WR 840N TL-WR840N 300MBps ...,https://tokopedia.com/belsa/jaringan-tp-link-t...,155000.0,263000,263000.0
4,"Oct 22, 2022",TL WR840N,TPLink TL-WR840N Router Wireless WiFi 300Mbps ...,https://tokopedia.com/ccwinta/tplink-tl-wr840n...,155000.0,236000,236000.0
...,...,...,...,...,...,...,...
2004,"Oct 15, 2022",TL WR840N,Wireless Router TP-Link TL-WR840N,https://shopee.co.id/Wireless-Router-TP-Link-T...,155000.0,155000,155000.0
2005,"Oct 15, 2022",TL WR840N,Tp-Link / Tplink Tl-Wr840N Wireless-N300 Router,https://shopee.co.id/Tp-Link-Tplink-Tl-Wr840N-...,155000.0,227000,227000.0
2006,"Oct 15, 2022",TL WR840N,TP-Link / TPLink TL-WR840N Wireless-N300 Route...,https://shopee.co.id/TP-Link-TPLink-TL-WR840N-...,155000.0,220000,220000.0
2007,"Oct 15, 2022",TL WR840N,TP-LINK TPLINK TL-WR840N Wireless N Router Rep...,https://shopee.co.id/TP-LINK-TPLINK-TL-WR840N-...,155000.0,214000,214000.0
2008,"Oct 15, 2022",TL WR840N,TP-LINK TL-WR840N 300Mbps Wireless N Router,https://shopee.co.id/TP-LINK-TL-WR840N-300Mbps...,155000.0,410000,410000.0

In [174]:
plt = figure add_subplot(figsize=(10,4))
add_subplot(1,2,1)
plt.(df(['SKU Name']), kind="kde")
add_subplot(1,2,2)
plt.show()

SyntaxError: invalid syntax (3194290357.py, line 1)